alias zl='eza -al --color=always --group-directories-first --icons'
alias za='eza -alh --color=always --group-directories-first --icons'
alias zt='eza -aT --color=always --group-directories-first --icons'
alias fixpacman="doas rm -rf /var/lib/pacman/db.lck"
alias wget='wget -c '
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias .1='cd ..'
alias .2='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias home='cd ~'
alias mx='chmod a+x'
alias 000='chmod -R 000'
alias 644='chmod -R 644'
alias 666='chmod -R 666'
alias 755='chmod -R 755'
alias 777='chmod -R 777'
alias h="history | grep "
alias f="find . | grep "
alias tree='tree -CAhF --dirsfirst'
alias treed='tree -CAFd'
alias mountedinfo='df -hT'
alias mkarch.tar='tar -cvf'
alias mkarch.bz2='tar -cvjf'
alias mkarch.gz='tar -cvzf'
alias unarch.tar='tar -xvf'
alias unarch.bz2='tar -xvjf'
alias unarch.gz='tar -xvzf'
alias gc1='git clone --depth=1'
alias gitsubmodupd='git submodule update --init --recursive'
alias cls='clear'
alias gpul='git pull'
alias gp='gpul'
alias gpus='git push'
alias nv='nvim'
alias vim='nvim'
alias vi='nvim'
alias v='nvim'
alias nvf='nix run github:notashelf/nvf#maximal --extra-experimental-features "nix-command flakes"'
alias lb='/opt/ladybird/usr/bin/Ladybird'
alias vid='mpv --vo=tct --really-quiet yes --profile=sw-fast'
