alias yayf="yay -Slq | fzf --multi --preview 'yay -Sii {1}' --preview-window=down:75% | xargs -ro yay -S"
alias zl='eza -al --color=always --group-directories-first --icons'
alias za='eza -alh --color=always --group-directories-first --icons'
alias zt='eza -aT --color=always --group-directories-first --icons'
alias z.="eza -a | grep -e '^\.'"
alias grubup="sudo grub-mkconfig -o /boot/grub/grub.cfg"
alias fixpacman="sudo rm -rf /var/lib/pacman/db.lck"
alias wget='wget -c '
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias .1='cd ..'
alias .2='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias grep='rg'
alias ls='za'
alias find='fd'
alias sudo='doas'
alias home='cd ~'
alias mx='chmod a+x'
alias 000='chmod -R 000'
alias 644='chmod -R 644'
alias 666='chmod -R 666'
alias 755='chmod -R 755'
alias 777='chmod -R 777'
alias h="history | grep "
alias f="find . | grep "
alias tree='tree -CAhF --dirsfirst'
alias treed='tree -CAFd'
alias mountedinfo='df -hT'
alias mktar='tar -cvf'
alias mkbz2='tar -cvjf'
alias mkgz='tar -cvzf'
alias untar='tar -xvf'
alias unbz2='tar -xvjf'
alias ungz='tar -xvzf'
alias gc1='git clone --depth=1'
alias gitsubmodupd='git submodule update --init --recursive'
alias nv='nvim'
alias cls='clear'
alias linutil='curl -fsSL christitus.com/linux | sh'
alias gpul='git pull'
alias gp='gpul'
alias gpus='git push'
alias vim='nvim'
alias vi='nvim'
alias lb='/opt/ladybird/usr/bin/Ladybird'
alias vid='mpv --vo=tct --really-quiet yes --profile=sw-fast'
alias qpush='git add . && git commit -m update && git push'
alias screen-time='niri-screen-time -from 1970-01-01 | nvim -R'
