gappih=0
gappiv=0
gappoh=0
gappov=0
scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9
borderpx=2
rootcolor=0x313244ff
bordercolor=0x313244ff
focuscolor=0xf5c2e7ff
maximizescreencolor=0xa6e3a1ff
urgentcolor=0xf38ba8ff
scratchpadcolor=0x89b4faff
globalcolor=0xcba6f7ff
overlaycolor=0x94e2d5ff
